### PR TITLE
add protected routes using sapper-rbac

### PR DESCRIPTION
**Pull request by primavera133**
Second shot; now using sapper-rbac. Seems I had to add the unrestricet route ( '/.*') last to make it work properly.

### CODE REVIEW

**Comment by primavera133** [comment]
I dunno, maybe you want to add this as a branch too, to keep the original example clean?

**Comment by antony** [comment]
@primavera133 I'm going to have a think about how I want to handle addons such as this yeah - it might be a lot of maintenance, but it also might be a nice idea to keep things clean as you say.

**Comment by patrickleet** [comment]
probably want `?` in those regexes as everything past there is optional

```
'/admin?.*'
```

I built on both of your work here, replacing the backend with keycloak, and using passport + cookie-session instead of something custom:

https://github.com/CloudNativeEntrepreneur/sapper-authentication-demo

**Comment by ajayfsm** [comment]
@primavera133  the /profile route seems unprotected and throws an error when accessed after logging out

**Pull request closed without merging**
